In [1]:
print("Hello, I'm excited to learn PyTorch")

Hello, I'm excited to learn PyTorch


In [2]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7 , 7])

In [8]:
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
#MATRIX
MATRIX = torch.tensor([[7 , 8],
                       [8, 9]])
MATRIX

tensor([[7, 8],
        [8, 9]])

In [12]:
MATRIX.ndim


2

In [13]:
MATRIX[1]

tensor([8, 9])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
#Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 8, 4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 8, 4]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 8, 4]])

In [19]:
#Random Tensors
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3251, 0.5107, 0.0540, 0.1348],
        [0.7258, 0.5989, 0.4988, 0.2358],
        [0.4164, 0.6268, 0.5164, 0.4790]])

In [20]:
random_tensor.ndim

2

In [21]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))

In [22]:
random_image_size_tensor.ndim

3

In [23]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [24]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

In [28]:
ones*random_tensor

tensor([[0.3251, 0.5107, 0.0540, 0.1348],
        [0.7258, 0.5989, 0.4988, 0.2358],
        [0.4164, 0.6268, 0.5164, 0.4790]])

In [29]:
 torch.range(1,4)

<ipython-input-29-0e6280fdbe25>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,4)


tensor([1., 2., 3., 4.])

In [30]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
 #Tensor Data Types
 float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,
                                device=None,
                                requires_grad=False)
 float_32_tensor

tensor([3., 6., 9.])

In [33]:
  float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [38]:
int_32_tensor.shape

torch.Size([3])

In [39]:
int_32_tensor.device

device(type='cpu')

In [40]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0427, 0.5576, 0.5557, 0.3179],
        [0.5899, 0.8064, 0.8214, 0.6098],
        [0.8992, 0.0779, 0.5892, 0.5037]])

In [41]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.0427, 0.5576, 0.5557, 0.3179],
        [0.5899, 0.8064, 0.8214, 0.6098],
        [0.8992, 0.0779, 0.5892, 0.5037]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [42]:
# Manipulating Tensors or Tensor Operations
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [43]:
tensor * 10

tensor([10, 20, 30])

In [44]:
tensor

tensor([1, 2, 3])

In [45]:
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [46]:
tensor - 10

tensor([ 0, 10, 20])

In [47]:
# Try out PyTorch inbuilt functions
tensor

tensor([10, 20, 30])

In [48]:
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [49]:
torch.add(tensor, 10)

tensor([20, 30, 40])

In [50]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [51]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] + tensor[i]
print(value)

tensor(120)
CPU times: user 967 µs, sys: 713 µs, total: 1.68 ms
Wall time: 1.99 ms


In [52]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.61 ms, sys: 96 µs, total: 1.7 ms
Wall time: 1.96 ms


tensor(1400)

In [53]:
tensor @ tensor

tensor(1400)

In [54]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [55]:
# torch.mm(tensor_A, tensor_B)
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [56]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [57]:
#To fix tensor shape issues, we can manipulate the shape of one of our tensors using transpose
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [58]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [59]:
tensor_B.T.shape

torch.Size([2, 3])

In [60]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [61]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [62]:
# Tensor Aggregations(min, max, mean, sum)
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
torch.min(x)

tensor(0)

In [64]:
torch.max(x)

tensor(90)

In [65]:
x.dtype

torch.int64

In [66]:
torch.mean(x)

RuntimeError: ignored

In [67]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [68]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [69]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [70]:
x.argmin()

tensor(0)

In [71]:
x[0]

tensor(0)

In [72]:
x = torch.arange(1,101,10)

In [73]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [74]:
x.argmin()

tensor(0)

In [75]:
x[0]

tensor(1)

In [76]:
x.argmax()

tensor(9)

In [77]:
x[9]

tensor(91)

In [84]:
# Reshaping, stacking, squeezing and unsquezeeing tensors
x = torch.arange(1., 10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [85]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [86]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [87]:
z[:, 0] = 5

In [88]:
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [93]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [94]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [95]:
x_reshaped.shape

torch.Size([1, 9])

In [98]:
x_reshaped.squeeze().shape

torch.Size([9])

In [97]:
x_reshaped.shape

torch.Size([1, 9])

In [100]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


In [101]:
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [102]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

In [103]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [104]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [105]:
x[0][0]

tensor([1, 2, 3])

In [111]:
x[0][2][2]

tensor(9)

In [112]:
x[:, 0]

tensor([[1, 2, 3]])

In [113]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [115]:
x[:, 1, 1]

tensor([5])

In [116]:
x[0,0,:]

tensor([1, 2, 3])

In [117]:
x[0][2][2]

tensor(9)

In [118]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [120]:
# Numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [121]:
tensor.dtype

torch.float32

In [122]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [123]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

In [124]:
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [125]:
numpy_tensor.dtype

dtype('float32')

In [126]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))