In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


In [2]:
 ## Reproducibility (trying to take random out of random)
 torch.rand(3,3)

tensor([[0.1671, 0.2346, 0.8613],
        [0.3730, 0.3393, 0.3578],
        [0.1967, 0.8665, 0.7624]])

In [3]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5135, 0.0747, 0.0072, 0.3538],
        [0.6204, 0.2781, 0.9903, 0.4656],
        [0.8756, 0.8884, 0.8083, 0.9336]])
tensor([[0.7073, 0.8882, 0.0778, 0.5951],
        [0.4093, 0.5572, 0.6421, 0.2218],
        [0.8679, 0.8317, 0.7420, 0.3344]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [4]:
# Let's make some random and reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [5]:
# Running tensors and PyTorch objects on the GPUs (and making faster computations)
!nvidia-smi

Fri Dec  1 05:30:42 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [6]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [7]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [8]:
# Count number of devices
torch.cuda.device_count()

1

In [9]:
# Putting tensors (and models) on the GPU
# Using GPU results in faster computations
tensor = torch.tensor([1, 2, 3], device="cpu")

print(tensor, tensor.device)



tensor([1, 2, 3]) cpu


In [10]:
# MOve tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [11]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [15]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])

In [16]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [17]:
# Excersises and extra curriculam
random_tensor = torch.rand(7,7)

In [18]:
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])